# Generated by Django 3.2.4 on 2021-06-10 01:40

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField(default=1)),
                ('metodo_pagamento', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('numero_documento', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_pedido', to='pedido.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='PagamentoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_id', models.CharField(blank=True, db_index=True, max_length=250)),
                ('mercado_pago_status', models.CharField(blank=True, max_length=250)),
                ('mercado_pago_status_detail', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_mercado_pago', to='pagamento.pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento do MP',
                'verbose_name_plural': 'Pagamentos do MP',
                'db_table': 'pagamento_mercado_pago',
            },
        ),
    ]
