# Generated by Django 3.2.4 on 2021-06-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_gateway_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='peoplesoft_endereco_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='peoplesoft_pessoa_id',
            field=models.PositiveIntegerField(),
        ),
    ]
