# Generated by Django 3.2.5 on 2021-07-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_pedido_frete_dimona_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='frete_dimona_id',
        ),
    ]
