# Generated by Django 3.2.5 on 2021-07-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_pedido_endereco_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='peoplesoft_endereco_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='peoplesoft_pessoa_id',
        ),
    ]
