# Generated by Django 3.2.9 on 2022-01-26 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0018_auto_20210910_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
