# Generated by Django 3.2.9 on 2022-01-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0019_pedido_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='session_ativa',
            field=models.BooleanField(default=False),
        ),
    ]
