# Generated by Django 3.2.4 on 2021-06-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_item_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
