# Generated by Django 3.2.4 on 2021-06-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_alter_produtovariacao_tipo_variacao'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
