# Generated by Django 3.2.4 on 2021-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210616_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='abandonado',
            field=models.BooleanField(default=True),
        ),
    ]
