# Generated by Django 3.2.4 on 2021-06-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_auto_20210624_1948'),
        ('checkout', '0008_item_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_modelo', to='catalogo.modeloproduto'),
        ),
    ]
