# Generated by Django 3.2.5 on 2021-08-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20210630_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='modelo',
            new_name='modelo_produto',
        ),
    ]
