# Generated by Django 3.2.9 on 2022-02-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0020_pedido_session_ativa'),
        ('checkout', '0012_auto_20210909_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
        ),
    ]
