# Generated by Django 3.2.3 on 2021-05-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('I', 'Infantil'), ('B', 'Bebê / Body'), ('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
    ]
