# Generated by Django 3.2.4 on 2021-06-08 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_auto_20210607_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovariacao',
            name='tipo_variacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_variacao_produto', to='catalogo.tipovariacao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, default=45.9, max_digits=999, verbose_name='Preço base'),
        ),
    ]
