# Generated by Django 3.2.4 on 2021-06-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_auto_20210608_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtovariacao',
            name='tipo_variacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_variacao_produto', to='catalogo.tipovariacao'),
        ),
    ]
