# Generated by Django 3.2.4 on 2021-06-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_produtovariacao_tipo_variacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, default=45.9, max_digits=999, verbose_name='Preço base'),
        ),
    ]
