# Generated by Django 3.2.4 on 2021-06-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_produtovariacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
