# Generated by Django 3.2.5 on 2021-07-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0035_tipovariacao_sku_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovariacao',
            name='sku_seller',
        ),
    ]
