# Generated by Django 3.2.5 on 2021-08-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0044_modelo_descricao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovariacao',
            name='valor_adicional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
