# Generated by Django 3.2.5 on 2021-08-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0046_merge_20210804_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloproduto',
            name='descricao_cliente',
        ),
    ]
