# Generated by Django 3.2.5 on 2021-09-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0049_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
