# Generated by Django 4.0.4 on 2022-05-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0066_tipoproduto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoTipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.produto')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipoproduto')),
            ],
            options={
                'db_table': 'produto_tipo_produto',
                'ordering': ('created_at',),
            },
        ),
    ]
