# Generated by Django 4.0.5 on 2022-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0067_modelo_tipo_produto_produtoimagem_tipo_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='descricao_produto',
            field=models.TextField(default='SEM_INFORMACAO', verbose_name='Descrição produto'),
        ),
    ]
