# Generated by Django 4.0.4 on 2022-05-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0067_produtotipoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoimagem',
            name='tipo_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipoproduto'),
        ),
    ]
