# Generated by Django 4.0.4 on 2022-05-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0068_produtoimagem_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='tipo_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipoproduto'),
        ),
    ]
