# Generated by Django 4.0.4 on 2022-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0069_modelo_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='imagem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
