# Generated by Django 4.0.5 on 2022-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0070_alter_modelo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='imagem_medidas',
            field=models.CharField(default='NAO_INFORMADO', max_length=50),
        ),
    ]
