# Generated by Django 3.2.4 on 2021-06-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='nome_contato',
            field=models.CharField(default='Marcelo Ostia', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='telefone_contato',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='referencia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
