# Generated by Django 3.2.5 on 2021-07-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20210707_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_dimona_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
