# Generated by Django 3.2.4 on 2021-06-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_carrinho_abandonado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
