# Generated by Django 3.2.4 on 2021-07-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0031_alter_modelovariacao_options'),
        ('checkout', '0009_alter_item_modelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemCarrinho',
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item do carrinho', 'verbose_name_plural': 'Itens do carrinho'},
        ),
        migrations.AlterModelTable(
            name='itemcarrinho',
            table='item_carrinho',
        ),
    ]
