# Generated by Django 3.2 on 2021-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='icone_fontawesome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
