# Generated by Django 3.2 on 2021-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_produtoimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoimagem',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descricao'),
        ),
    ]
