# Generated by Django 3.2 on 2021-05-15 18:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_produtoimagem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_principal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
