# Generated by Django 3.2 on 2021-05-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_produto_imagem_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ('nome',), 'verbose_name': 'subcategoria', 'verbose_name_plural': 'subcategorias'},
        ),
    ]
