# Generated by Django 3.2 on 2021-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_produto_preco_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10, verbose_name='Preço base'),
        ),
    ]
