# Generated by Django 3.2.4 on 2021-06-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_produtovariacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TipoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacao_tipo_variacao', to='catalogo.variacao')),
            ],
            options={
                'verbose_name': 'Tipo Variação',
                'verbose_name_plural': 'Tipos Variações',
                'db_table': 'tipo_variacao',
                'ordering': ('descricao',),
            },
        ),
    ]
