# Generated by Django 3.2.4 on 2021-06-24 15:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovariacao',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem Variação'),
        ),
    ]
