# Generated by Django 3.2.4 on 2021-06-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_item_modelo'),
        ('catalogo', '0029_auto_20210627_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoVariacao',
            new_name='ModeloVariacao',
        ),
        migrations.AlterModelOptions(
            name='modelovariacao',
            options={'ordering': ('-created_at',), 'verbose_name': 'Variação do modelo', 'verbose_name_plural': 'Variações do modelo'},
        ),
        migrations.AlterModelTable(
            name='modelovariacao',
            table='modelo_variacao',
        ),
    ]
