# Generated by Django 3.2.4 on 2021-06-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_auto_20210627_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelovariacao',
            options={'ordering': ('created_at',), 'verbose_name': 'Variação do modelo', 'verbose_name_plural': 'Variações do modelo'},
        ),
    ]
