# Generated by Django 3.2.5 on 2021-07-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_seller_ativo'),
        ('catalogo', '0031_alter_modelovariacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seller.seller'),
        ),
    ]
