# Generated by Django 3.2.5 on 2021-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0039_auto_20210723_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloproduto',
            name='nome',
            field=models.CharField(choices=[('TRADICIONAL', 'Tradicional'), ('BABYLOOK', 'T-Shirt Feminina'), ('MANGALONGA', 'Manga Longa'), ('REGATA', 'Regata')], max_length=50),
        ),
    ]
