# Generated by Django 3.2.5 on 2021-08-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0042_alter_skudimona_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloproduto',
            options={'ordering': ('-created_at',), 'verbose_name': 'Modelos', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.RemoveField(
            model_name='modeloproduto',
            name='nome',
        ),
    ]
