# Generated by Django 3.2.5 on 2021-08-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0044_modeloproduto_descricao_cliente'),
        ('catalogo', '0045_tipovariacao_valor_adicional'),
    ]

    operations = [
    ]
