# Generated by Django 3.2.5 on 2021-09-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0051_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='order_exibicao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='order_exibicao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
