# Generated by Django 3.2.5 on 2021-09-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0054_produtoimagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovariacao',
            name='variacao',
        ),
        migrations.DeleteModel(
            name='ModeloVariacao',
        ),
        migrations.DeleteModel(
            name='TipoVariacao',
        ),
        migrations.DeleteModel(
            name='Variacao',
        ),
    ]
