# Generated by Django 3.2.5 on 2021-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0055_auto_20210910_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='mostrar_tela_inicial',
            field=models.BooleanField(default=True),
        ),
    ]
