# Generated by Django 3.2.5 on 2021-10-13 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0057_alter_produto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamanhoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.modelo')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.tamanho')),
            ],
            options={
                'verbose_name': 'tamanho',
                'verbose_name_plural': 'Tamanhos',
                'db_table': 'tamanho_modelo',
                'ordering': ('created_at',),
            },
        ),
    ]
