# Generated by Django 3.2.9 on 2021-12-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0060_precomodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=51.9, max_digits=10, verbose_name='Valor'),
        ),
        migrations.DeleteModel(
            name='PrecoModelo',
        ),
    ]
