# Generated by Django 3.2.12 on 2022-02-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0061_auto_20211223_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('-created_at',), 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
