# Generated by Django 4.0.2 on 2022-02-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0063_categoria_icone_fontawesome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.modelo')),
            ],
            options={
                'verbose_name': 'Cor e Modelos',
                'verbose_name_plural': 'Cores e Modelos',
                'db_table': 'cor_modelo',
                'ordering': ('created_at',),
            },
        ),
    ]
