# Generated by Django 4.0.5 on 2022-06-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0066_tipoproduto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='tipo_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipoproduto'),
        ),
        migrations.AddField(
            model_name='produtoimagem',
            name='tipo_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipoproduto'),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='imagem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
