# Generated by Django 4.0.5 on 2022-06-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0068_modelo_descricao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='slug',
            field=models.SlugField(default='informar-manualmente', max_length=100),
        ),
    ]
