# Generated by Django 3.2.4 on 2021-07-01 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0005_auto_20210627_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='EventoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.SlugField(default='likeestampa', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='evento.status')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_pedido', to='pedido.pedido')),
            ],
            options={
                'verbose_name': 'Evento do pedido',
                'verbose_name_plural': 'Evento dos pedidos',
                'db_table': 'evento_pedido',
            },
        ),
    ]
