# Generated by Django 3.2.4 on 2021-07-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='visivel_cliente',
            field=models.BooleanField(default=True),
        ),
    ]
