# Generated by Django 3.2.4 on 2021-07-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_status_visivel_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopedido',
            name='evento_atual',
            field=models.BooleanField(default=False),
        ),
    ]
