# Generated by Django 4.0.4 on 2022-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_eventopedido_evento_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopedido',
            name='data_ocorrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
