# Generated by Django 3.2.4 on 2021-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20210617_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='telefone_contato',
            field=models.CharField(default='', max_length=12),
        ),
    ]
