# Generated by Django 3.2.5 on 2021-07-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20210627_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='frete_tipo',
            field=models.CharField(blank=True, choices=[('proprio', 'Frete proprio'), ('mercado_envio', 'Mercado Envios')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='frete_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='frete_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
