# Generated by Django 3.2.5 on 2021-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20210713_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
