# Generated by Django 3.2.4 on 2021-06-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='metodo_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_pedido',
        ),
        migrations.RemoveField(
            model_name='pagamentomercadopago',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='pagamentomercadopago',
            name='installments',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Parcelas'),
        ),
        migrations.AddField(
            model_name='pagamentomercadopago',
            name='payment_method_id',
            field=models.CharField(default='master', max_length=250, verbose_name='Método de Pagamento'),
        ),
        migrations.AddField(
            model_name='pagamentomercadopago',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=10, verbose_name='Valor da Transação'),
        ),
        migrations.AlterField(
            model_name='pagamentomercadopago',
            name='mercado_pago_id',
            field=models.CharField(blank=True, db_index=True, default=1, max_length=250),
        ),
        migrations.AlterField(
            model_name='pagamentomercadopago',
            name='mercado_pago_status',
            field=models.CharField(blank=True, default='approved', max_length=250),
        ),
        migrations.AlterField(
            model_name='pagamentomercadopago',
            name='mercado_pago_status_detail',
            field=models.CharField(blank=True, default='accredited', max_length=250),
        ),
    ]
