# Generated by Django 3.2.5 on 2021-07-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0007_auto_20210627_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoMercadoPagoWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_request', models.JSONField()),
                ('webhook_data_recebimento', models.DateTimeField(auto_now=True)),
                ('webhook_executado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('mercado_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamento.pagamentomercadopago')),
            ],
            options={
                'db_table': 'mercado_pago_webhook',
            },
        ),
    ]
