# Generated by Django 3.2.4 on 2021-06-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_auto_20210620_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='gateway_pagamento',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('pagseguro_uol', 'PagSeguro UOL')], default='mercado_pago', max_length=20),
        ),
    ]
