# Generated by Django 3.2.4 on 2021-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0006_pagamentomercadopago_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentomercadopago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='pagamentomercadopago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
