# Generated by Django 3.2 on 2021-05-15 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_produto_imagem_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_principal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem principal'),
        ),
    ]
