# Generated by Django 3.2.4 on 2021-06-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoVariacao',
        ),
    ]
