# Generated by Django 3.2.4 on 2021-06-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_auto_20210624_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloproduto',
            name='nome',
            field=models.CharField(choices=[('TRADICIONAL', 'Tradicional'), ('BABYLOOK', 'Baby Look'), ('MANGALONGA', 'Manga Longa'), ('REGATA', 'Regata')], max_length=50),
        ),
    ]
