# Generated by Django 3.2.5 on 2021-07-14 16:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0033_auto_20210713_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_design',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem design'),
        ),
    ]
