# Generated by Django 3.2.5 on 2021-07-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0034_produto_imagem_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovariacao',
            name='sku_seller',
            field=models.CharField(max_length=50, null=True, verbose_name='SKU Seller'),
        ),
    ]
