# Generated by Django 3.2.5 on 2021-08-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0040_alter_modeloproduto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuDimona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.modelo')),
            ],
            options={
                'verbose_name': 'SKUs Dimona',
                'verbose_name_plural': 'SKU Dimona',
                'db_table': 'sku_dimona',
                'ordering': ('created_at',),
            },
        ),
    ]
