# Generated by Django 3.2.5 on 2021-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0041_skudimona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skudimona',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
