# Generated by Django 3.2.5 on 2021-08-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0047_remove_modeloproduto_descricao_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelovariacao',
            old_name='modelo',
            new_name='modelo_produto',
        ),
    ]
