# Generated by Django 3.2.5 on 2021-09-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0052_auto_20210909_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'ordering': ('order_exibicao',), 'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='tamanho',
            options={'ordering': ('order_exibicao',), 'verbose_name': 'tamanho', 'verbose_name_plural': 'Tamanhos'},
        ),
    ]
