# Generated by Django 3.2.5 on 2021-09-10 01:47

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0053_auto_20210909_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Mockup')),
                ('order_exibicao', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_imagem', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Produto Imagem',
                'verbose_name_plural': 'Imagens',
                'db_table': 'produto_imagem',
                'ordering': ('order_exibicao',),
            },
        ),
    ]
