# Generated by Django 4.0.4 on 2022-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0065_rename_categoria_tipoproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='descricao',
            field=models.TextField(default='Descrição não informada'),
        ),
    ]
