# Generated by Django 3.2.4 on 2021-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210618_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='peoplesoft_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
