# Generated by Django 3.2.5 on 2021-07-16 16:29

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20210627_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', localflavor.br.models.BRStateField(max_length=2)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Brasil', max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
            ],
            options={
                'db_table': 'endereco_cliente',
            },
        ),
    ]
