# Generated by Django 3.2.5 on 2021-07-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20210716_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='peoplesoft_id',
        ),
    ]
