# Generated by Django 3.2.5 on 2021-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_itempedido_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='seller',
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete_nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
