# Generated by Django 3.2.5 on 2021-07-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_auto_20210713_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
