# Generated by Django 3.2.5 on 2021-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_auto_20210719_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='request_seller',
            field=models.JSONField(blank=True, null=True, verbose_name='Request feito no seller'),
        ),
    ]
