# Generated by Django 3.2.5 on 2021-08-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_pedido_request_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='modelo',
            new_name='modelo_produto',
        ),
    ]
