# Generated by Django 3.2.5 on 2021-09-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0054_produtoimagem'),
        ('pedido', '0017_rename_modelo_itempedido_modelo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_pedido_cor', to='catalogo.cor'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_pedido_tamanho', to='catalogo.tamanho'),
        ),
    ]
